'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const B=require('../outputs/business-engine.cjs'),M=require('../outputs/operations-model.js'),{createStorage}=require('../outputs/storage.cjs'),{createProviders}=require('../outputs/business-providers.cjs'),{createTTS}=require('../outputs/tts-service.cjs');
async function main(){
 const s=M.initial(),at='2026-09-13T08:00:00Z',issue={url:'https://temmuzonline.com/pages/iletisim',code:'h1',title:'0 H1 bulundu.',severity:'high',action:'Ana başlığı kontrol et.'};s.growth.checks=[{at,issues:[issue,{...issue}],pages:[]}];const report=M.makeReport(s,{now:Date.parse(at),id:'business-test'});B.ingestReport(s,report);B.ingestReport(s,report);assert.equal(s.business.findings.length,1);assert.equal(s.business.findings[0].sourceTimestamp,at);assert.equal(s.business.findings[0].url,issue.url);
 const f=s.business.findings[0],a=B.createAction(s,{findingId:f.findingId});assert.equal(B.createAction(s,{findingId:f.findingId}).actionId,a.actionId);B.updateAction(s,a.actionId,{status:'DONE'});assert.equal(a.verifiedAt,null);assert.throws(()=>B.updateAction(s,a.actionId,{status:'VERIFIED'}));B.verifyActions(s,{at:'2099-01-01T00:00:00Z',issues:[],pages:[]});assert.equal(a.status,'DONE');B.verifyActions(s,{at:'2099-01-01T00:00:00Z',issues:[],pages:[{url:issue.url,status:200}]});assert.equal(a.status,'VERIFIED');
 const dependency=B.createAction(s,{title:'Bağımlılık'}),p=B.createProcess(s,{title:'SEO düzeltmesi',stages:[{title:'Düzeltme',dependencies:[dependency.actionId]},{title:'Kontrol'}]});assert.equal(p.status,'BLOCKED');B.updateAction(s,dependency.actionId,{status:'DONE'});B.processState(s,p);assert.equal(p.nextAction,'Düzeltme');
 B.event(s,'INTEGRATION_FAILED','google','ga4','GA4 başarısız',{},'high');B.event(s,'INTEGRATION_FAILED','google','ga4','GA4 başarısız',{},'high');assert.equal(s.business.notifications.filter(n=>n.message==='GA4 başarısız').length,1);
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jarvis-business-'));try{const storage=createStorage({TEMMUZ_DATA_DIR:dir,STORAGE_MODE:'json'});storage.save({configRevision:5,state:s});const restored=M.hydrate(storage.load().state);assert.equal(restored.business.actions[0].actionId,a.actionId);assert.equal(restored.business.actions[0].status,'VERIFIED');assert.equal(restored.business.processes[0].processId,p.processId);assert.equal(storage.load().configRevision,5);}finally{fs.rmSync(dir,{recursive:true,force:true});}
 assert.equal(B.risk('getGoogle'),'READ_ONLY');assert.equal(B.risk('changePrice'),'HIGH_RISK');
 const providers=createProviders({});assert.equal(providers.status().ai.status,'SETUP_REQUIRED');assert.equal(providers.status().tts.status,'SETUP_REQUIRED');await assert.rejects(providers.tts({text:'test'}));await assert.rejects(providers.stt({audio:'test'}));await assert.rejects(providers.image(s,{}));
 let ttsBody=null;const tts=createTTS({VOICE_JARVIS_ENABLED:'true',TTS_PROVIDER:'openai',TTS_MODEL:'gpt-4o-mini-tts',TTS_VOICE:'cedar',AI_API_KEY:'fixture-key'},async(url,options)=>{ttsBody=JSON.parse(options.body);return new Response(Buffer.from('fixture-audio'));});const spoken=await tts.speak({text:'Merhaba TemmuzOnline'});assert.equal(spoken.provider,'openai');assert.equal(ttsBody.voice,'cedar');assert.match(ttsBody.instructions,/Türkçe konuş/);assert.ok(!JSON.stringify(ttsBody).includes('fixture-key'));
 s.business.content.push({contentId:'draft',title:'Test',platform:'Instagram',format:'text',status:'DRAFT'});await assert.rejects(providers.publish(s,{contentId:'draft',approved:true}));B.contentStatus(s,'draft','WAITING_APPROVAL');B.contentStatus(s,'draft','APPROVED');const job=await providers.publish(s,{contentId:'draft',approved:true});assert.equal(job.status,'BLOCKED');assert.equal(s.business.content[0].status,'APPROVED');
 const answer=await providers.chat(s,{text:'Bugün ne yaptın?',context:{kind:'Latest report'}});assert.equal(answer.setupRequired,true);assert.equal(s.business.messages.length,2);assert.ok(B.daily(s).activities.every(a=>a.result));assert.doesNotMatch(JSON.stringify(providers.status()),/access_token|client_secret/);
 const configured=createProviders({AI_CHAT_ENABLED:'true',AI_PROVIDER:'openai',AI_API_KEY:'test-key',AI_MODEL:'test-model',IMAGE_GENERATION_ENABLED:'true',IMAGE_PROVIDER:'openai',IMAGE_API_KEY:'image-key'},async(url,options)=>String(url).includes('/chat/completions')?Response.json({choices:[{message:{content:JSON.stringify({decisions:['Karar: kampanya planı onaylandı'],pendingActions:['Yapılacak: ürün sayfasını düzelt']})}}]}):Response.json({data:[{url:'https://cdn.example.test/generated.png',revised_prompt:'verified prompt'}]}));assert.equal(configured.status().images.status,'CONFIGURED_UNVERIFIED');const asset=await configured.image({visualPrompt:'TemmuzOnline ürün görseli',format:'1:1'});assert.equal(asset.provider,'openai');const extracted=await configured.memoryExtract('Karar: kampanya planı onaylandı\nYapılacak: ürün sayfasını düzelt');assert.ok(extracted.decisions.length&&extracted.pendingActions.length);
 console.log('PASS: phase 1-3 persistence, exact findings, actions, verified recheck, processes, events, notifications, memory and disabled providers.');
}main().catch(e=>{console.error(e);process.exitCode=1;});
