'use strict';
const assert=require('node:assert/strict');
const {postgresStorage}=require('../outputs/postgres-storage.cjs');
const M=require('../outputs/operations-model.js');
const B=require('../outputs/executive-brief.js');
class FakePool{constructor(){this.rows=[];this.queries=[];}on(){}async query(sql,params=[]){this.queries.push(sql);if(sql.startsWith('CREATE'))return {rows:[]};if(sql.startsWith('SELECT config_revision'))return {rows:this.rows};if(sql.startsWith('SELECT NOW'))return {rows:[{checked_at:new Date(),updated_at:null}]};if(sql.startsWith('INSERT')){if(!this.rows.length)this.rows=[{config_revision:params[0],state:JSON.parse(params[1])}];return {rows:[{id:'singleton'}]};}throw new Error('unexpected query');}async end(){}}
const env={DATABASE_URL:'postgresql://USER:PASSWORD@HOST/DB?sslmode=require'};const pool=new FakePool();
(async()=>{const s=postgresStorage(env,FakePool);const state=M.initial(),value={configRevision:7,state};assert.equal(await s.load(),null);await s.save(value);const loaded=await s.load();assert.equal(loaded.configRevision,7);assert.equal(loaded.state.version,12);assert.equal((await s.health()).persistent,true);assert.throws(()=>postgresStorage({},FakePool),/DATABASE_URL tanımlı değil/);
 const report=M.makeReport(state,{id:'brief-test'}),brief=B.make(state,report);assert.equal(brief.kpis.length<=5,true);assert.equal(brief.actions.length<=3,true);assert.equal(brief.risks.length<=2,true);assert.equal(brief.opportunities.length<=2,true);assert.equal(brief.confidence,'example');assert.match(brief.voiceScript,/Günaydın/);assert.match(brief.voiceScript,/Detaylar panelde\.$/);
 const persisted=M.initial();M.appendReport(persisted,report,Date.now(),{storage:{persistent:false},google:{lastError:'Google bağlantısı başarısız'},googleError:true});assert.equal(persisted.reports.length,1);assert.equal(persisted.briefs.length,1);assert.match(persisted.briefs[0].risks.join(' '),/Google bağlantısı/);M.appendReport(persisted,report,Date.now(),{storage:{persistent:false},google:{lastError:'Google bağlantısı başarısız'},googleError:true});assert.equal(persisted.briefs.length,1);const hydrated=M.hydrate(persisted);assert.equal(hydrated.reports.length,1);assert.equal(hydrated.briefs.length,1);const healthy=M.initial();M.appendReport(healthy,report,Date.now(),{storage:{persistent:true},google:{},googleError:false});assert.doesNotMatch(healthy.briefs[0].risks.join(' '),/Google bağlantısı/);
 const slotState=M.initial(),slot=M.slotAt(slotState,Date.now());if(slot){const scheduled=M.makeReport(slotState,{slot,now:Date.now()});M.appendReport(slotState,scheduled,Date.now(),{storage:{persistent:true},google:{},googleError:false});M.appendReport(slotState,scheduled,Date.now(),{storage:{persistent:true},google:{},googleError:false});assert.equal(slotState.reports.filter(r=>r.id===scheduled.id).length,1);assert.equal(slotState.briefs.filter(b=>b.reportId===scheduled.id).length,1);}
 const old=M.hydrate({version:12,experts:state.experts,settings:state.settings,growth:state.growth,reports:state.reports,messages:[]});assert.deepEqual(old.briefs,[]);console.log('PASS: postgres adapter contract, health, missing DATABASE_URL, executive brief bounds/voice, legacy hydration.');})().catch(e=>{console.error(e);process.exitCode=1;});
